### ISSUE TITLE
basic_example.json fails during routine verification 

### ISSUE THREAD

**Issue by bdg221** [PsiQ/bartiq#104]
## Describe the bug
After reading in basic_example.json, trying to run `compile_routine` results in the following error:

```
Traceback (most recent call last):
  File "/Users/xxx/Documents/PsiQuantum/brian/bartiq/src/bartiq/test2.py", line 10, in <module>
    compiled_routine = compile_routine(uncompiled_routine)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Documents/PsiQuantum/brian/bartiq/src/bartiq/compilation/_compile.py", line 86, in compile_routine
    return _compile_routine(routine, backend, precompilation_stages, global_functions, functions_map, skip_verification)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Documents/PsiQuantum/brian/bartiq/src/bartiq/compilation/_compile.py", line 102, in _compile_routine
    raise BartiqCompilationError(
bartiq.errors.BartiqCompilationError: Found the following issues with the provided routine before the compilation started: ['N is present in linked_params, but not in input_params.\n']
```

This is the result of changes made in #76 which introduced routine verification.

## How to Reproduce
The following code will reproduce the error:
```
import json
from bartiq import Routine, compile_routine, evaluate
from bartiq.integrations import qref_to_bartiq

with open("docs/data/basic_example.json", "r") as f:
    routine_dict = json.load(f)

uncompiled_routine = qref_to_bartiq(routine_dict)
compiled_routine = compile_routine(uncompiled_routine)
```

## Expected behavior
It is expected that the provided JSON file can be read and used to generated a compiled routine.

## Actual behavior
An error is thrown:
```
bartiq.errors.BartiqCompilationError: Found the following issues with the provided routine before the compilation started: ['N is present in linked_params, but not in input_params.\n']
```

## Environment:**
 - OS: OSX, 
 - Bartiq 0.5.0
 - Python 3.11.9

**Comment by bdg221** [comment]
After more research, it appears that the warning is a result of a bug. Before the compilation (after precompile), the resources have the following values:
`a` -> `{'T_gates': <Resource name="T_gates" value="2*N_a">}`
`b` -> `{'T_gates': <Resource name="T_gates" value="N_b*ceil(log_2(N_b))">}`

After compilation, the resources have the following values:
`a` -> `{'T_gates': <Resource name="T_gates" value="2*N">}`
`b` -> `{'T_gates': <Resource name="T_gates" value="N_b*ceiling(log2(N_b))">}`

During the compilation `N_b` is not replaced with `N`. This explains why the warning is only for `N_b`.

If you agree, I will open a new issue for the compilation bug and will leave this issue for correcting basic_example.json to include `input_params`.

**Comment by mstechly** [comment]
Hey @bdg221, thanks a lot for finding this!
Please put it on hold for now, as we're making some refactors which might solve it and I don't want you to waste time on this if that's the case.
