### ISSUE TITLE
Add `as_native_type` to backend

### ISSUE THREAD

**Issue by mstechly** [PsiQ/bartiq#131]
## Is your feature request related to a problem? If so, please describe it.
Currently there's a somewhat weird pattern in some of the tests, where in the input QREF a value is an `int`, but it becomes a `str` in the result.

This is because in the serialization process we cast all the values to strings.

For tests it's a minor issue, but it forces extra parsing in certain situations, which complicates logic unnecessarily and adds inefficiencies.

## How you envision the solution

We could add a `as_native_type` method to `SymbolicBackend`, which would work similarly to `serialize`, but would return native python types when possible, rather than strings.

**Comment by dexter2206** [comment]
Solved via #135
