### ISSUE TITLE
README links to "basic_usage" that does not exist

### ISSUE THREAD

**Issue by bdg221** [PsiQ/bartiq#36]
In README.md, the following line appears:
```
To go step by step through the process and see how you can use bartiq for your algorithms, please take a look at our tutorials, starting with [basic_usage](https://github.com/PsiQ/bartiq/blob/main/basic_usage.md).
```

However, that page does not exist. I'm not sure if there will be a page there in the future or if you meant to point to one of these pages:

https://github.com/PsiQ/bartiq/blob/main/docs/tutorials/01_basic_example.ipynb
https://github.com/PsiQ/bartiq/blob/main/docs/tutorials/index.md

**Comment by mstechly** [comment]
Thanks @bdg221, good catch! I created a PR to fix it in #43 :)
