### ISSUE TITLE
Missing tests for `propagate_linked_params`

### ISSUE THREAD

**Issue by mstechly** [PsiQ/bartiq#70]
Apparently we don't have any unit tests for `propagate_linked_params`, would be good to add them.

**Comment by bdg221** [comment]
@mstechly @dexter2206 I had a question about the correct behavior of `propagate_linked_params`. Can you confirm that the effects seen are correct. Below are the comparisons of values before and after calling `propagate_linked_params`:

uncompiled_routine = after `qref_to_bartiq`  
precompiled_routine = after `propagate_linked_params`:
![image](https://github.com/user-attachments/assets/9bbeb707-0707-44d3-bdf9-0e55bdb99897) 
![image](https://github.com/user-attachments/assets/462b44dd-dbc7-41d7-a2ee-1982dd72845d)

![image](https://github.com/user-attachments/assets/75c5baac-72fc-4958-bb2a-3fb51d2650df) 
![image](https://github.com/user-attachments/assets/91a76218-43ac-496e-b03a-03a7a43eec13)


![image](https://github.com/user-attachments/assets/7f18fb60-9fb8-44cd-a096-b44c909a67b9)
![image](https://github.com/user-attachments/assets/6efa3e32-9eeb-4b3f-9d5c-bbcf85e054d9)

 
![image](https://github.com/user-attachments/assets/b762d4ea-0cbc-43dc-a982-b6dea5cff0a0)
![image](https://github.com/user-attachments/assets/7ac79e17-22ae-4659-99ce-d6c5beb7d3fe)
