### ISSUE TITLE
Change local_variables to be a dictionary

### ISSUE THREAD

**Issue by mstechly** [PsiQ/bartiq#71]
Right now `local_variables` are expressed as a string of form `A = B*C`.
This is problematic, as it requires parsing this expression.

We should refactor `local_variables` to be a dictionary: `{"A": "B*C"}`, it will simplify logic in a couple of places.

While doing this refactor, one should also find all the occurences of `split_equation` and see if it makes sense to refactor them as well.

**Comment by dexter2206** [comment]
Fixed via #79
